export enum PermissionEnum {
  'add_permission' = 'add_permission',
  'change_permission' = 'change_permission',
  'delete_permission' = 'delete_permission',
  'add_group' = 'add_group',
  'change_group' = 'change_group',
  'delete_group' = 'delete_group',
  'add_content-type' = 'add_content-type',
  'change_content-type' = 'change_content-type',
  'delete_content-type' = 'delete_content-type',
  'add_user' = 'add_user',
  'change_user' = 'change_user',
  'delete_user' = 'delete_user',
  'read_user' = 'read_user',
  'read_group' = 'read_group',
  'read_permission' = 'read_permission',
  'read_content-type' = 'read_content-type',
  'change_profile' = 'change_profile',
  'read_themes-page' = 'read_themes-page',
  'read_account-page' = 'read_account-page',
  'read_profile-frame' = 'read_profile-frame',
  'read_admin-page' = 'read_admin-page',
  'read_groups-frame' = 'read_groups-frame',
  'read_users-frame' = 'read_users-frame',
}
